default_platform(:ios)

platform :ios do
  desc "Generate App Store screenshots"
  lane :screenshots do
    capture_screenshots(
      workspace: "ios/1000Rejections.xcworkspace",
      scheme: "1000Rejections",
      output_directory: "fastlane/screenshots",
      clear_previous_screenshots: true
    )
  end
end
