# App Store required screenshot sizes (iPad 13-inch required because supportsTablet: true)
devices([
  "iPad Pro 13-inch (M4)"
])

languages(["en-US"])

scheme("1000Rejections")
test_target_name("ScreenshotUITests")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
stop_after_first_error(false)
override_status_bar(true)
